version: '3.8'

services:
  api:
    build:
      context: .
      target: builder
    command: npm run start:dev
    volumes:
      - .:/code
      - ./node_modules:/code/node_modules
    ports:
      - 3000:3000
